In [1]:
import pandas as pd
import wbgapi as wb
from tqdm import tqdm
import pickle as pkl

# Explore Help Functions

In [2]:
list(wb.series.list())[0]

{'id': 'AG.AGR.TRAC.NO', 'value': 'Agricultural machinery, tractors'}

In [3]:
wb.source.info()

id    name                                                                  code      concepts  lastupdated
----  --------------------------------------------------------------------  ------  ----------  -------------
1     Doing Business                                                        DBS              3  2021-08-18
2     World Development Indicators                                          WDI              3  2023-03-01
3     Worldwide Governance Indicators                                       WGI              3  2022-09-23
5     Subnational Malnutrition Database                                     SNM              3  2016-03-21
6     International Debt Statistics                                         IDS              4  2022-12-06
11    Africa Development Indicators                                         ADI              3  2013-02-22
12    Education Statistics                                                  EDS              3  2020-12-20
13    Enterprise Surveys                                                    ESY              3  2022-03-25
14    Gender Statistics                                                     GDS              3  2023-03-06
15    Global Economic Monitor                                               GEM              3  2020-07-27
16    Health Nutrition and Population Statistics                            HNP              3  2022-12-23
18    IDA Results Measurement System                                        IDA              3  2021-07-23
19    Millennium Development Goals                                          MDG              3  2018-09-19
20    Quarterly Public Sector Debt                                          PSD              3  2023-02-09
22    Quarterly External Debt Statistics SDDS                               QDS              3  2023-01-31
23    Quarterly External Debt Statistics GDDS                               QDG              3  2023-01-31
25    Jobs                                                                  JOB              3  2022-06-29
27    Global Economic Prospects                                             GEP              3  2023-01-10
28    Global Financial Inclusion                                            FDX              3  2022-10-24
29    The Atlas of Social Protection: Indicators of Resilience and Equity   GSP              3  2021-12-20
30    Exporter Dynamics Database â€“ Indicators at Country-Year Level         ED1              3  2016-03-31
31    Country Policy and Institutional Assessment                           CPI              3  2022-09-15
32    Global Financial Development                                          GFD              3  2022-09-23
33    G20 Financial Inclusion Indicators                                    G2F              3  2019-02-27
34    Global Partnership for Education                                      GPE              3  2013-04-12
35    Sustainable Energy for All                                            SE4              3  2018-06-30
37    LAC Equity Lab                                                        LEL              3  2016-04-06
38    Subnational Poverty                                                   SNP              3  2015-04-27
39    Health Nutrition and Population Statistics by Wealth Quintile         HNQ              3  2022-12-13
40    Population estimates and projections                                  HPP              3  2022-12-23
41    Country Partnership Strategy for India (FY2013 - 17)                  CPS              3  2015-05-22
43    Adjusted Net Savings                                                  WAT              3  2022-09-20
45    Indonesia Database for Policy and Economic Research                   IDD              3  2022-08-11
46    Sustainable Development Goals                                         SDG              3  2022-07-22
50    Subnational Population                                                SNT              3  2017-09-21
54    Joint External Debt Hub                                               JED              3  2023-01-30
57    WDI Database Archives                                                 WDA              4  2023-03-08
58    Universal Health Coverage                                             UHC              3  2019-04-25
59    Wealth Accounts                                                       WAC              3  2021-10-27
60    Economic Fitness                                                      EFT              3  2018-04-19
61    PPPs Regulatory Quality                                               PRQ              3  2019-04-25
62    International Comparison Program (ICP) 2011                           ICP              4  2020-08-24
63    Human Capital Index                                                   HCI              3  2020-09-21
64    Worldwide Bureaucracy Indicators                                      WBI              3  2022-09-20
65    Health Equity and Financial Protection Indicators                     HPI              3  2019-11-06
66    Logistics Performance Index                                           LPI              3  2019-10-29
67    PEFA 2011                                                             PF1              4  2022-11-23
68    PEFA 2016                                                             PF6              4  2023-01-12
69    Global Financial Inclusion and Consumer Protection Survey             RFA              3  2019-06-27
70    Economic Fitness 2                                                    EF2              3  2022-07-21
71    International Comparison Program (ICP) 2005                           IC5              4  2021-09-10
73    Global Financial Inclusion and Consumer Protection Survey (Internal)  RFI              3  2019-06-27
75    Environment, Social and Governance (ESG) Data                         ESG              3  2023-03-02
76    Remittance Prices Worldwide (Sending Countries)                       RWS              3  2020-12-07
77    Remittance Prices Worldwide (Receiving Countries)                     RWR              3  2020-12-07
78    ICP 2017                                                              IC7              4  2020-10-21
79    PEFA_GRPFM                                                            GRP              4  2022-12-18
80    Gender Disaggregated Labor Database (GDLD)                            GDL              4  2020-07-25
81    International Debt Statistics: DSSI                                   DSI              4  2022-12-06
82    Global Public Procurement                                             GPP              3  2021-03-24
83    Statistical Performance Indicators (SPI)                              SPI              3  2021-04-01
84    Education Policy                                                      EDP              3  2023-01-30
85    PEFA_2021_SNG                                                         SNG              4  2023-03-06
86    Global Jobs Indicators Database (JOIN)                                JON              3  2021-09-24
87    Country Climate and Development Report (CCDR)                         CCD              3  2022-10-07
88    Food Prices for Nutrition                                             FPN              4  2022-07-05
89    Identification for Development (ID4D) Data                            ID4              3  2022-12-21
      67 elements

In [4]:
wb.economy.info(db = 2)

id    value                                                 region    incomeLevel
----  ----------------------------------------------------  --------  -------------
ABW   Aruba                                                 LCN       HIC
AFE   Africa Eastern and Southern
AFG   Afghanistan                                           SAS       LIC
AFW   Africa Western and Central
AGO   Angola                                                SSF       LMC
ALB   Albania                                               ECS       UMC
AND   Andorra                                               ECS       HIC
ARB   Arab World
ARE   United Arab Emirates                                  MEA       HIC
ARG   Argentina                                             LCN       UMC
ARM   Armenia                                               ECS       UMC
ASM   American Samoa                                        EAS       UMC
ATG   Antigua and Barbuda                                   LCN       HIC
AUS   Australia                                             EAS       HIC
AUT   Austria                                               ECS       HIC
AZE   Azerbaijan                                            ECS       UMC
BDI   Burundi                                               SSF       LIC
BEL   Belgium                                               ECS       HIC
BEN   Benin                                                 SSF       LMC
BFA   Burkina Faso                                          SSF       LIC
BGD   Bangladesh                                            SAS       LMC
BGR   Bulgaria                                              ECS       UMC
BHR   Bahrain                                               MEA       HIC
BHS   Bahamas, The                                          LCN       HIC
BIH   Bosnia and Herzegovina                                ECS       UMC
BLR   Belarus                                               ECS       UMC
BLZ   Belize                                                LCN       UMC
BMU   Bermuda                                               NAC       HIC
BOL   Bolivia                                               LCN       LMC
BRA   Brazil                                                LCN       UMC
BRB   Barbados                                              LCN       HIC
BRN   Brunei Darussalam                                     EAS       HIC
BTN   Bhutan                                                SAS       LMC
BWA   Botswana                                              SSF       UMC
CAF   Central African Republic                              SSF       LIC
CAN   Canada                                                NAC       HIC
CEB   Central Europe and the Baltics
CHE   Switzerland                                           ECS       HIC
CHI   Channel Islands                                       ECS       HIC
CHL   Chile                                                 LCN       HIC
CHN   China                                                 EAS       UMC
CIV   Cote d'Ivoire                                         SSF       LMC
CMR   Cameroon                                              SSF       LMC
COD   Congo, Dem. Rep.                                      SSF       LIC
COG   Congo, Rep.                                           SSF       LMC
COL   Colombia                                              LCN       UMC
COM   Comoros                                               SSF       LMC
CPV   Cabo Verde                                            SSF       LMC
CRI   Costa Rica                                            LCN       UMC
CSS   Caribbean small states
CUB   Cuba                                                  LCN       UMC
CUW   Curacao                                               LCN       HIC
CYM   Cayman Islands                                        LCN       HIC
CYP   Cyprus                                                ECS       HIC
CZE   Czechia                                               ECS       HIC
DEU   Germany                                               ECS       HIC
DJI   Djibouti                                              MEA       LMC
DMA   Dominica                                              LCN       UMC
DNK   Denmark                                               ECS       HIC
DOM   Dominican Republic                                    LCN       UMC
DZA   Algeria                                               MEA       LMC
EAP   East Asia & Pacific (excluding high income)
EAR   Early-demographic dividend
EAS   East Asia & Pacific
ECA   Europe & Central Asia (excluding high income)
ECS   Europe & Central Asia
ECU   Ecuador                                               LCN       UMC
EGY   Egypt, Arab Rep.                                      MEA       LMC
EMU   Euro area
ERI   Eritrea                                               SSF       LIC
ESP   Spain                                                 ECS       HIC
EST   Estonia                                               ECS       HIC
ETH   Ethiopia                                              SSF       LIC
EUU   European Union
FCS   Fragile and conflict affected situations
FIN   Finland                                               ECS       HIC
FJI   Fiji                                                  EAS       UMC
FRA   France                                                ECS       HIC
FRO   Faroe Islands                                         ECS       HIC
FSM   Micronesia, Fed. Sts.                                 EAS       LMC
GAB   Gabon                                                 SSF       UMC
GBR   United Kingdom                                        ECS       HIC
GEO   Georgia                                               ECS       UMC
GHA   Ghana                                                 SSF       LMC
GIB   Gibraltar                                             ECS       HIC
GIN   Guinea                                                SSF       LIC
GMB   Gambia, The                                           SSF       LIC
GNB   Guinea-Bissau                                         SSF       LIC
GNQ   Equatorial Guinea                                     SSF       UMC
GRC   Greece                                                ECS       HIC
GRD   Grenada                                               LCN       UMC
GRL   Greenland                                             ECS       HIC
GTM   Guatemala                                             LCN       UMC
GUM   Guam                                                  EAS       HIC
GUY   Guyana                                                LCN       UMC
HIC   High income
HKG   Hong Kong SAR, China                                  EAS       HIC
HND   Honduras                                              LCN       LMC
HPC   Heavily indebted poor countries (HIPC)
HRV   Croatia                                               ECS       HIC
HTI   Haiti                                                 LCN       LMC
HUN   Hungary                                               ECS       HIC
IBD   IBRD only
IBT   IDA & IBRD total
IDA   IDA total
IDB   IDA blend
IDN   Indonesia                                             EAS       LMC
IDX   IDA only
IMN   Isle of Man                                           ECS       HIC
IND   India                                                 SAS       LMC
INX   Not classified
IRL   Ireland                                               ECS       HIC
IRN   Iran, Islamic Rep.                                    MEA       LMC
IRQ   Iraq                                                  MEA       UMC
ISL   Iceland                                               ECS       HIC
ISR   Israel                                                MEA       HIC
ITA   Italy                                                 ECS       HIC
JAM   Jamaica                                               LCN       UMC
JOR   Jordan                                                MEA       UMC
JPN   Japan                                                 EAS       HIC
KAZ   Kazakhstan                                            ECS       UMC
KEN   Kenya                                                 SSF       LMC
KGZ   Kyrgyz Republic                                       ECS       LMC
KHM   Cambodia                                              EAS       LMC
KIR   Kiribati                                              EAS       LMC
KNA   St. Kitts and Nevis                                   LCN       HIC
KOR   Korea, Rep.                                           EAS       HIC
KWT   Kuwait                                                MEA       HIC
LAC   Latin America & Caribbean (excluding high income)
LAO   Lao PDR                                               EAS       LMC
LBN   Lebanon                                               MEA       LMC
LBR   Liberia                                               SSF       LIC
LBY   Libya                                                 MEA       UMC
LCA   St. Lucia                                             LCN       UMC
LCN   Latin America & Caribbean
LDC   Least developed countries: UN classification
LIC   Low income
LIE   Liechtenstein                                         ECS       HIC
LKA   Sri Lanka                                             SAS       LMC
LMC   Lower middle income
LMY   Low & middle income
LSO   Lesotho                                               SSF       LMC
LTE   Late-demographic dividend
LTU   Lithuania                                             ECS       HIC
LUX   Luxembourg                                            ECS       HIC
LVA   Latvia                                                ECS       HIC
MAC   Macao SAR, China                                      EAS       HIC
MAF   St. Martin (French part)                              LCN       HIC
MAR   Morocco                                               MEA       LMC
MCO   Monaco                                                ECS       HIC
MDA   Moldova                                               ECS       UMC
MDG   Madagascar                                            SSF       LIC
MDV   Maldives                                              SAS       UMC
MEA   Middle East & North Africa
MEX   Mexico                                                LCN       UMC
MHL   Marshall Islands                                      EAS       UMC
MIC   Middle income
MKD   North Macedonia                                       ECS       UMC
MLI   Mali                                                  SSF       LIC
MLT   Malta                                                 MEA       HIC
MMR   Myanmar                                               EAS       LMC
MNA   Middle East & North Africa (excluding high income)
MNE   Montenegro                                            ECS       UMC
MNG   Mongolia                                              EAS       LMC
MNP   Northern Mariana Islands                              EAS       HIC
MOZ   Mozambique                                            SSF       LIC
MRT   Mauritania                                            SSF       LMC
MUS   Mauritius                                             SSF       UMC
MWI   Malawi                                                SSF       LIC
MYS   Malaysia                                              EAS       UMC
NAC   North America
NAM   Namibia                                               SSF       UMC
NCL   New Caledonia                                         EAS       HIC
NER   Niger                                                 SSF       LIC
NGA   Nigeria                                               SSF       LMC
NIC   Nicaragua                                             LCN       LMC
NLD   Netherlands                                           ECS       HIC
NOR   Norway                                                ECS       HIC
NPL   Nepal                                                 SAS       LMC
NRU   Nauru                                                 EAS       HIC
NZL   New Zealand                                           EAS       HIC
OED   OECD members
OMN   Oman                                                  MEA       HIC
OSS   Other small states
PAK   Pakistan                                              SAS       LMC
PAN   Panama                                                LCN       HIC
PER   Peru                                                  LCN       UMC
PHL   Philippines                                           EAS       LMC
PLW   Palau                                                 EAS       UMC
PNG   Papua New Guinea                                      EAS       LMC
POL   Poland                                                ECS       HIC
PRE   Pre-demographic dividend
PRI   Puerto Rico                                           LCN       HIC
PRK   Korea, Dem. People's Rep.                             EAS       LIC
PRT   Portugal                                              ECS       HIC
PRY   Paraguay                                              LCN       UMC
PSE   West Bank and Gaza                                    MEA       LMC
PSS   Pacific island small states
PST   Post-demographic dividend
PYF   French Polynesia                                      EAS       HIC
QAT   Qatar                                                 MEA       HIC
ROU   Romania                                               ECS       HIC
RUS   Russian Federation                                    ECS       UMC
RWA   Rwanda                                                SSF       LIC
SAS   South Asia
SAU   Saudi Arabia                                          MEA       HIC
SDN   Sudan                                                 SSF       LIC
SEN   Senegal                                               SSF       LMC
SGP   Singapore                                             EAS       HIC
SLB   Solomon Islands                                       EAS       LMC
SLE   Sierra Leone                                          SSF       LIC
SLV   El Salvador                                           LCN       LMC
SMR   San Marino                                            ECS       HIC
SOM   Somalia                                               SSF       LIC
SRB   Serbia                                                ECS       UMC
SSA   Sub-Saharan Africa (excluding high income)
SSD   South Sudan                                           SSF       LIC
SSF   Sub-Saharan Africa
SST   Small states
STP   Sao Tome and Principe                                 SSF       LMC
SUR   Suriname                                              LCN       UMC
SVK   Slovak Republic                                       ECS       HIC
SVN   Slovenia                                              ECS       HIC
SWE   Sweden                                                ECS       HIC
SWZ   Eswatini                                              SSF       LMC
SXM   Sint Maarten (Dutch part)                             LCN       HIC
SYC   Seychelles                                            SSF       HIC
SYR   Syrian Arab Republic                                  MEA       LIC
TCA   Turks and Caicos Islands                              LCN       HIC
TCD   Chad                                                  SSF       LIC
TEA   East Asia & Pacific (IDA & IBRD countries)
TEC   Europe & Central Asia (IDA & IBRD countries)
TGO   Togo                                                  SSF       LIC
THA   Thailand                                              EAS       UMC
TJK   Tajikistan                                            ECS       LMC
TKM   Turkmenistan                                          ECS       UMC
TLA   Latin America & the Caribbean (IDA & IBRD countries)
TLS   Timor-Leste                                           EAS       LMC
TMN   Middle East & North Africa (IDA & IBRD countries)
TON   Tonga                                                 EAS       UMC
TSA   South Asia (IDA & IBRD)
TSS   Sub-Saharan Africa (IDA & IBRD countries)
TTO   Trinidad and Tobago                                   LCN       HIC
TUN   Tunisia                                               MEA       LMC
TUR   Turkiye                                               ECS       UMC
TUV   Tuvalu                                                EAS       UMC
TZA   Tanzania                                              SSF       LMC
UGA   Uganda                                                SSF       LIC
UKR   Ukraine                                               ECS       LMC
UMC   Upper middle income
URY   Uruguay                                               LCN       HIC
USA   United States                                         NAC       HIC
UZB   Uzbekistan                                            ECS       LMC
VCT   St. Vincent and the Grenadines                        LCN       UMC
VEN   Venezuela, RB                                         LCN       INX
VGB   British Virgin Islands                                LCN       HIC
VIR   Virgin Islands (U.S.)                                 LCN       HIC
VNM   Vietnam                                               EAS       LMC
VUT   Vanuatu                                               EAS       LMC
WLD   World
WSM   Samoa                                                 EAS       LMC
XKX   Kosovo                                                ECS       UMC
YEM   Yemen, Rep.                                           MEA       LIC
ZAF   South Africa                                          SSF       UMC
ZMB   Zambia                                                SSF       LIC
ZWE   Zimbabwe                                              SSF       LMC
      266 elements

In [5]:
wb.data.DataFrame('NY.GDP.PCAP.CD').reset_index()

,economy,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,...,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021
0,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25609.955724,26515.678080,26942.307976,28421.386493,28451.273745,29326.708058,30220.594523,31650.760537,24487.863560,29342.100858
1,AFE,162.913034,162.551683,172.002460,199.189238,179.387799,198.230368,209.414665,211.707060,224.239783,...,1759.182395,1730.394686,1719.183721,1538.552268,1443.692371,1628.586788,1564.734340,1512.270553,1363.540741,1549.772730
2,AFG,62.369375,62.443703,60.950364,82.021738,85.511073,105.243196,143.103233,167.165675,134.012768,...,663.141053,651.987862,628.146804,592.476537,520.252064,530.149831,502.056771,500.522664,516.866552,368.754614
3,AFW,106.976475,112.047561,117.730633,122.278715,130.599963,137.186142,142.895375,127.303606,128.365494,...,1953.407033,2149.295219,2243.271464,1876.623483,1645.023767,1585.911930,1731.311792,1749.303317,1683.436391,1757.030626
4,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4962.552072,5101.983876,5059.080441,3100.830685,1709.515534,2283.214233,2487.500996,2142.238757,1603.993477,1953.533757
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3410.859780,3704.784221,3902.676013,3520.766449,3759.560246,4009.380987,4384.048892,4416.108358,4310.811183,5269.783901
262,YEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1349.990295,1497.747941,1557.601406,1488.416482,1069.817122,893.716573,701.714878,NaN,NaN,NaN
263,ZAF,529.561923,543.042224,560.699395,601.599951,642.688431,681.131112,718.118179,775.152812,813.508497,...,8173.869138,7441.230854,6965.137897,6204.929901,5735.066787,6734.475153,7048.522211,6688.787271,5741.643129,7055.044776
264,ZMB,228.567399,216.274674,208.562685,209.453362,236.941713,296.022427,334.672528,350.653425,398.557506,...,1729.647471,1840.320553,1724.576220,1307.909649,1249.923143,1495.752138,1475.204538,1268.120941,956.831364,1137.343633
265,ZWE,276.643363,279.332656,275.966139,277.532515,282.376856,294.893605,279.337779,295.056449,302.802871,...,1290.193956,1408.367810,1407.034293,1410.329174,1421.787789,1192.107012,2269.177012,1421.868596,1372.696674,1773.920411

# Pull in Trade Data for Oldest and Newest Years

In [6]:
trade_data1 = pd.read_stata("country_partner_sitcproduct4digit_year_1962.dta") 
trade_data2 = pd.read_stata("country_partner_sitcproduct4digit_year_2018.dta")

In [7]:
country_list1 = list(trade_data1["location_code"]) + list(trade_data1["partner_code"])
country_list1 = list(set(country_list1))

country_list2 = list(trade_data2["location_code"]) + list(trade_data2["partner_code"])
country_list2 = list(set(country_list2))

In [8]:
len(country_list1)

156

In [9]:
len(country_list2)

236

In [10]:
economic_indicator = wb.data.DataFrame('NY.GDP.PCAP.CD').reset_index()

In [11]:
economic_indicator[~pd.isna(economic_indicator.YR1960) & economic_indicator.economy.isin(country_list1)]

,economy,YR1960,YR1961,YR1962,YR1963,YR1964,YR1965,YR1966,YR1967,YR1968,...,YR2012,YR2013,YR2014,YR2015,YR2016,YR2017,YR2018,YR2019,YR2020,YR2021
2,AFG,62.369375,62.443703,60.950364,82.021738,85.511073,105.243196,143.103233,167.165675,134.012768,...,663.141053,651.987862,628.146804,592.476537,520.252064,530.149831,502.056771,500.522664,516.866552,368.754614
13,AUS,1810.510249,1877.509803,1854.552575,1967.014259,2131.277657,2280.902108,2343.706917,2579.986339,2723.999484,...,68044.714816,68158.579743,62513.411217,56710.445724,49875.565143,53936.140255,57207.871509,54941.434179,51720.370763,60443.109165
14,AUT,935.460427,1031.815004,1087.834243,1167.000532,1269.412583,1374.532140,1486.968606,1569.667183,1677.673528,...,48564.917335,50731.127254,51786.377175,44195.817595,45307.587862,47429.158456,51466.556563,50070.403348,48809.226876,53637.705711
16,BDI,71.360224,72.088782,73.942008,78.948269,85.964725,50.990420,51.808640,54.450305,54.647466,...,238.205949,241.547671,257.818552,289.359633,242.065671,243.135809,231.446477,216.972968,216.826741,221.477676
17,BEL,1273.691659,1350.197673,1438.523233,1535.023729,1701.846276,1835.594766,1957.626080,2086.636005,2222.361511,...,44670.560685,46757.951856,47764.071512,41008.296719,42012.622719,44198.482391,47544.981147,46638.681305,45517.794930,51247.014353
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,URY,491.213493,604.176627,659.611697,587.006885,744.879993,705.398553,668.328011,584.850133,578.588983,...,15206.872620,17015.134761,16875.506193,15655.936998,16766.425259,18769.787523,18825.283807,17859.931496,15619.542656,17313.188348
251,USA,3007.123445,3066.562869,3243.843078,3374.515171,3573.941185,3827.527110,4146.316646,4336.426587,4695.923390,...,51784.418574,53291.127689,55123.849787,56762.729452,57866.744934,59907.754261,62823.309438,65120.394663,63530.633484,70248.629000
253,VCT,155.293588,163.424034,166.602193,154.653976,163.883606,165.126044,173.196917,167.777520,160.299923,...,6754.370184,7117.554763,7210.616623,7386.737595,7684.779208,8030.585057,8399.694011,8674.371009,8335.256476,8666.387041
254,VEN,953.677944,968.767091,1022.034029,1076.532443,864.265327,869.906867,877.196049,894.683818,940.201420,...,12937.927597,12433.980785,15975.729375,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,ZAF,529.561923,543.042224,560.699395,601.599951,642.688431,681.131112,718.118179,775.152812,813.508497,...,8173.869138,7441.230854,6965.137897,6204.929901,5735.066787,6734.475153,7048.522211,6688.787271,5741.643129,7055.044776

# Look at country coverage by each indicator

In [12]:
list_indicators = list(wb.series.list())

In [21]:
#load already processed data
with open('all_wb_indicators.pickle', 'rb') as handle:
    coverage = pkl.load(handle)

In [25]:
len(coverage)

1338

In [26]:
completed = [item[0] for item in coverage]

In [27]:
%%time
#coverage = []


for indicator in list_indicators:
    indicator_str = indicator["id"]
    
    print(indicator_str)
    
    if (indicator_str not in completed):
        #try: 
        indicator_df = wb.data.DataFrame(indicator_str).reset_index()

        coverage_1962 = len(indicator_df[~pd.isna(indicator_df.YR1962) \
                        & indicator_df.economy.isin(country_list1)])/len(country_list1)

        coverage_2020 = len(indicator_df[~pd.isna(indicator_df.YR2018) \
                        & indicator_df.economy.isin(country_list2)])/len(country_list2)

        coverage.append([indicator_str, indicator, coverage_1962, coverage_2020, indicator_df])
        
        with open('all_wb_indicators.pickle', 'wb') as handle:
            pkl.dump(coverage, handle)
        #except: 
        #    print(indicator_str)
        #    continue

AG.AGR.TRAC.NO
AG.CON.FERT.PT.ZS
AG.CON.FERT.ZS
AG.LND.AGRI.K2
AG.LND.AGRI.ZS
AG.LND.ARBL.HA
AG.LND.ARBL.HA.PC
AG.LND.ARBL.ZS
AG.LND.CREL.HA
AG.LND.CROP.ZS
AG.LND.EL5M.RU.K2
AG.LND.EL5M.RU.ZS
AG.LND.EL5M.UR.K2
AG.LND.EL5M.UR.ZS
AG.LND.EL5M.ZS
AG.LND.FRST.K2
AG.LND.FRST.ZS
AG.LND.IRIG.AG.ZS
AG.LND.PRCP.MM
AG.LND.TOTL.K2
AG.LND.TOTL.RU.K2
AG.LND.TOTL.UR.K2
AG.LND.TRAC.ZS
AG.PRD.CREL.MT
AG.PRD.CROP.XD
AG.PRD.FOOD.XD
AG.PRD.LVSK.XD
AG.SRF.TOTL.K2
AG.YLD.CREL.KG
BG.GSR.NFSV.GD.ZS
BM.GSR.CMCP.ZS
BM.GSR.FCTY.CD
BM.GSR.GNFS.CD
BM.GSR.INSF.ZS
BM.GSR.MRCH.CD
BM.GSR.NFSV.CD
BM.GSR.ROYL.CD
BM.GSR.TOTL.CD
BM.GSR.TRAN.ZS
BM.GSR.TRVL.ZS
BM.KLT.DINV.CD.WD
BM.KLT.DINV.WD.GD.ZS
BM.TRF.PRVT.CD
BM.TRF.PWKR.CD.DT
BN.CAB.XOKA.CD
BN.CAB.XOKA.GD.ZS
BN.FIN.TOTL.CD
BN.GSR.FCTY.CD
BN.GSR.GNFS.CD
BN.GSR.MRCH.CD
BN.KAC.EOMS.CD
BN.KLT.DINV.CD
BN.KLT.PTXL.CD
BN.RES.INCL.CD
BN.TRF.CURR.CD
BN.TRF.KOGT.CD
BX.GRT.EXTA.CD.WD
BX.GRT.TECH.CD.WD
BX.GSR.CCIS.CD
BX.GSR.CCIS.ZS
BX.GSR.CMCP.ZS
BX.GSR.FCTY.CD
BX.GSR.GNFS.CD
BX.GSR.INSF.ZS
BX.GSR.MRCH.CD
BX.GSR.NFSV.CD
BX.GSR.ROYL.CD
BX.GSR.TOTL.CD
BX.GSR.TRAN.ZS
BX.GSR.TRVL.ZS
BX.KLT.DINV.CD.WD
BX.KLT.DINV.WD.GD.ZS
BX.PEF.TOTL.CD.WD
BX.TRF.CURR.CD
BX.TRF.PWKR.CD
BX.TRF.PWKR.CD.DT
BX.TRF.PWKR.DT.GD.ZS
CM.MKT.INDX.ZG
CM.MKT.LCAP.CD
CM.MKT.LCAP.GD.ZS
CM.MKT.LDOM.NO
CM.MKT.TRAD.CD
CM.MKT.TRAD.GD.ZS
CM.MKT.TRNR
DC.DAC.AUSL.CD
DC.DAC.AUTL.CD
DC.DAC.BELL.CD
DC.DAC.CANL.CD
DC.DAC.CECL.CD
DC.DAC.CHEL.CD
DC.DAC.CZEL.CD
DC.DAC.DEUL.CD
DC.DAC.DNKL.CD
DC.DAC.ESPL.CD
DC.DAC.FINL.CD
DC.DAC.FRAL.CD
DC.DAC.GBRL.CD
DC.DAC.GRCL.CD
DC.DAC.HUNL.CD
DC.DAC.IRLL.CD
DC.DAC.ISLL.CD
DC.DAC.ITAL.CD
DC.DAC.JPNL.CD
DC.DAC.KORL.CD
DC.DAC.LUXL.CD
DC.DAC.NLDL.CD
DC.DAC.NORL.CD
DC.DAC.NZLL.CD
DC.DAC.POLL.CD
DC.DAC.PRTL.CD
DC.DAC.SVKL.CD
DC.DAC.SVNL.CD
DC.DAC.SWEL.CD
DC.DAC.TOTL.CD
DC.DAC.USAL.CD
DC.ODA.TLDC.CD
DC.ODA.TLDC.GN.ZS
DC.ODA.TOTL.CD
DC.ODA.TOTL.GN.ZS
DC.ODA.TOTL.KD
DT.DOD.DECT.CD
DT.DOD.DECT.GN.ZS
DT.DOD.DIMF.CD
DT.DOD.DLXF.CD
DT.DOD.DPNG.CD
DT.DOD.DPPG.CD
DT.DOD.DSTC.CD
DT.DOD.DSTC.IR.ZS
DT.DOD.DSTC.XP.ZS
DT.DOD.DSTC.ZS
DT.DOD.MIBR.CD
DT.DOD.MIDA.CD
DT.DOD.MWBG.CD
DT.DOD.PVLX.CD
DT.DOD.PVLX.EX.ZS
DT.DOD.PVLX.GN.ZS
DT.NFL.BLAT.CD
DT.NFL.BOND.CD
DT.NFL.DPNG.CD
DT.NFL.FAOG.CD
DT.NFL.IAEA.CD
DT.NFL.IFAD.CD
DT.NFL.ILOG.CD
DT.NFL.IMFC.CD
DT.NFL.IMFN.CD
DT.NFL.MIBR.CD
DT.NFL.MIDA.CD
DT.NFL.MLAT.CD
DT.NFL.MOTH.CD
DT.NFL.NIFC.CD
DT.NFL.OFFT.CD
DT.NFL.PBND.CD
DT.NFL.PCBK.CD
DT.NFL.PCBO.CD
DT.NFL.PNGB.CD
DT.NFL.PNGC.CD
DT.NFL.PROP.CD
DT.NFL.PRVT.CD
DT.NFL.RDBC.CD
DT.NFL.RDBN.CD
DT.NFL.UNAI.CD
DT.NFL.UNCF.CD
DT.NFL.UNCR.CD
DT.NFL.UNDP.CD
DT.NFL.UNEC.CD
DT.NFL.UNEP.CD
DT.NFL.UNFP.CD
DT.NFL.UNID.CD
DT.NFL.UNPB.CD
DT.NFL.UNRW.CD
DT.NFL.UNTA.CD
DT.NFL.UNWT.CD
DT.NFL.WFPG.CD
DT.NFL.WHOL.CD
DT.ODA.ALLD.CD
DT.ODA.ALLD.KD
DT.ODA.OATL.CD
DT.ODA.OATL.KD
DT.ODA.ODAT.CD
DT.ODA.ODAT.GI.ZS
DT.ODA.ODAT.GN.ZS
DT.ODA.ODAT.KD
DT.ODA.ODAT.MP.ZS
DT.ODA.ODAT.PC.ZS
DT.ODA.ODAT.XP.ZS
DT.TDS.DECT.CD
DT.TDS.DECT.EX.ZS
DT.TDS.DECT.GN.ZS
DT.TDS.DIMF.CD
DT.TDS.DPPF.XP.ZS
DT.TDS.DPPG.CD
DT.TDS.DPPG.GN.ZS
DT.TDS.DPPG.XP.ZS
DT.TDS.MLAT.CD
DT.TDS.MLAT.PG.ZS
EG.CFT.ACCS.RU.ZS
EG.CFT.ACCS.UR.ZS
EG.CFT.ACCS.ZS
EG.EGY.PRIM.PP.KD
EG.ELC.ACCS.RU.ZS
EG.ELC.ACCS.UR.ZS
EG.ELC.ACCS.ZS
EG.ELC.COAL.ZS
EG.ELC.FOSL.ZS
EG.ELC.HYRO.ZS
EG.ELC.LOSS.ZS
EG.ELC.NGAS.ZS
EG.ELC.NUCL.ZS
EG.ELC.PETR.ZS
EG.ELC.RNEW.ZS
EG.ELC.RNWX.KH
EG.ELC.RNWX.ZS
EG.FEC.RNEW.ZS
EG.GDP.PUSE.KO.PP
EG.GDP.PUSE.KO.PP.KD
EG.IMP.CONS.ZS
EG.USE.COMM.CL.ZS
EG.USE.COMM.FO.ZS
EG.USE.COMM.GD.PP.KD
EG.USE.CRNW.ZS
EG.USE.ELEC.KH.PC
EG.USE.PCAP.KG.OE
EN.ATM.CO2E.EG.ZS
EN.ATM.CO2E.GF.KT
EN.ATM.CO2E.GF.ZS
EN.ATM.CO2E.KD.GD
EN.ATM.CO2E.KT
EN.ATM.CO2E.LF.KT
EN.ATM.CO2E.LF.ZS
EN.ATM.CO2E.PC
EN.ATM.CO2E.PP.GD
EN.ATM.CO2E.PP.GD.KD
EN.ATM.CO2E.SF.KT
EN.ATM.CO2E.SF.ZS
EN.ATM.GHGO.KT.CE
EN.ATM.GHGO.ZG
EN.ATM.GHGT.KT.CE
EN.ATM.GHGT.ZG
EN.ATM.HFCG.KT.CE
EN.ATM.METH.AG.KT.CE
EN.ATM.METH.AG.ZS
EN.ATM.METH.EG.KT.CE
EN.ATM.METH.EG.ZS
EN.ATM.METH.KT.CE
EN.ATM.METH.ZG
EN.ATM.NOXE.AG.KT.CE
EN.ATM.NOXE.AG.ZS
EN.ATM.NOXE.EG.KT.CE
EN.ATM.NOXE.EG.ZS
EN.ATM.NOXE.KT.CE
EN.ATM.NOXE.ZG
EN.ATM.PFCG.KT.CE
EN.ATM.PM25.MC.M3
EN.ATM.PM25.MC.T1.ZS
EN.ATM.PM25.MC.T2.ZS
EN.ATM.PM25.MC.T3.ZS
EN.ATM.PM25.MC.ZS
EN.ATM.SF6G.KT.CE
EN.BIR.THRD.NO
EN.CLC.DRSK.XQ
EN.CLC.GHGR.MT.CE
EN.CLC.MDAT.ZS
EN.CO2.BLDG.ZS
EN.CO2.ETOT.ZS
EN.CO2.MANF.ZS
EN.CO2.OTHX.ZS
EN.CO2.TRAN.ZS
EN.FSH.THRD.NO
EN.HPT.THRD.NO
EN.MAM.THRD.NO
EN.POP.DNST
EN.POP.EL5M.RU.ZS
EN.POP.EL5M.UR.ZS
EN.POP.EL5M.ZS
EN.POP.SLUM.UR.ZS
EN.URB.LCTY
EN.URB.LCTY.UR.ZS
EN.URB.MCTY
EN.URB.MCTY.TL.ZS
EP.PMP.DESL.CD
EP.PMP.SGAS.CD
ER.FSH.AQUA.MT
ER.FSH.CAPT.MT
ER.FSH.PROD.MT
ER.GDP.FWTL.M3.KD
ER.H2O.FWAG.ZS
ER.H2O.FWDM.ZS
ER.H2O.FWIN.ZS
ER.H2O.FWST.ZS
ER.H2O.FWTL.K3
ER.H2O.FWTL.ZS
ER.H2O.INTR.K3
ER.H2O.INTR.PC
ER.LND.PTLD.ZS
ER.MRN.PTMR.ZS
ER.PTD.TOTL.ZS
FB.AST.NPER.ZS
FB.ATM.TOTL.P5
FB.BNK.CAPA.ZS
FB.CBK.BRCH.P5
FB.CBK.BRWR.P3
FB.CBK.DPTR.P3
FD.AST.PRVT.GD.ZS
FD.RES.LIQU.AS.ZS
FI.RES.TOTL.CD
FI.RES.TOTL.DT.ZS
FI.RES.TOTL.MO
FI.RES.XGLD.CD
FM.AST.CGOV.ZG.M3
FM.AST.DOMO.ZG.M3
FM.AST.DOMS.CN
FM.AST.NFRG.CN
FM.AST.PRVT.GD.ZS
FM.AST.PRVT.ZG.M3
FM.LBL.BMNY.CN
FM.LBL.BMNY.GD.ZS
FM.LBL.BMNY.IR.ZS
FM.LBL.BMNY.ZG
FP.CPI.TOTL
FP.CPI.TOTL.ZG
FP.WPI.TOTL
FR.INR.DPST
FR.INR.LEND
FR.INR.LNDP
FR.INR.RINR
FR.INR.RISK
FS.AST.CGOV.GD.ZS
FS.AST.DOMO.GD.ZS
FS.AST.DOMS.GD.ZS
FS.AST.PRVT.GD.ZS
FX.OWN.TOTL.40.ZS
FX.OWN.TOTL.60.ZS
FX.OWN.TOTL.FE.ZS
FX.OWN.TOTL.MA.ZS
FX.OWN.TOTL.OL.ZS
FX.OWN.TOTL.PL.ZS
FX.OWN.TOTL.SO.ZS
FX.OWN.TOTL.YG.ZS
FX.OWN.TOTL.ZS
GB.XPD.RSDV.GD.ZS
GC.AST.TOTL.CN
GC.AST.TOTL.GD.ZS
GC.DOD.TOTL.CN
GC.DOD.TOTL.GD.ZS
GC.LBL.TOTL.CN
GC.LBL.TOTL.GD.ZS
GC.NFN.TOTL.CN
GC.NFN.TOTL.GD.ZS
GC.NLD.TOTL.CN
GC.NLD.TOTL.GD.ZS
GC.REV.GOTR.CN
GC.REV.GOTR.ZS
GC.REV.SOCL.CN
GC.REV.SOCL.ZS
GC.REV.XGRT.CN
GC.REV.XGRT.GD.ZS
GC.TAX.EXPT.CN
GC.TAX.EXPT.ZS
GC.TAX.GSRV.CN
GC.TAX.GSRV.RV.ZS
GC.TAX.GSRV.VA.ZS
GC.TAX.IMPT.CN
GC.TAX.IMPT.ZS
GC.TAX.INTT.CN
GC.TAX.INTT.RV.ZS
GC.TAX.OTHR.CN
GC.TAX.OTHR.RV.ZS
GC.TAX.TOTL.CN
GC.TAX.TOTL.GD.ZS
GC.TAX.YPKG.CN
GC.TAX.YPKG.RV.ZS
GC.TAX.YPKG.ZS
GC.XPN.COMP.CN
GC.XPN.COMP.ZS
GC.XPN.GSRV.CN
GC.XPN.GSRV.ZS
GC.XPN.INTP.CN
GC.XPN.INTP.RV.ZS
GC.XPN.INTP.ZS
GC.XPN.OTHR.CN
GC.XPN.OTHR.ZS
GC.XPN.TOTL.CN
GC.XPN.TOTL.GD.ZS
GC.XPN.TRFT.CN
GC.XPN.TRFT.ZS
GF.XPD.BUDG.ZS
HD.HCI.OVRL
HD.HCI.OVRL.FE
HD.HCI.OVRL.LB
HD.HCI.OVRL.LB.FE
HD.HCI.OVRL.LB.MA
HD.HCI.OVRL.MA
HD.HCI.OVRL.UB
HD.HCI.OVRL.UB.FE
HD.HCI.OVRL.UB.MA
IC.BUS.DFRN.XQ
IC.BUS.DISC.XQ
IC.BUS.EASE.XQ
IC.BUS.NDNS.ZS
IC.BUS.NREG
IC.CRD.INFO.XQ
IC.CRD.PRVT.ZS
IC.CRD.PUBL.ZS
IC.CUS.DURS.EX
IC.ELC.DURS
IC.ELC.OUTG
IC.ELC.OUTG.ZS
IC.ELC.TIME
IC.EXP.CSBC.CD
IC.EXP.CSDC.CD
IC.EXP.TMBC
IC.EXP.TMDC
IC.FRM.BKWC.ZS
IC.FRM.BNKS.ZS
IC.FRM.BRIB.ZS
IC.FRM.CMPU.ZS
IC.FRM.CORR.ZS
IC.FRM.CRIM.ZS
IC.FRM.DURS
IC.FRM.FEMM.ZS
IC.FRM.FEMO.ZS
IC.FRM.FREG.ZS
IC.FRM.INFM.ZS
IC.FRM.METG.ZS
IC.FRM.OUTG.ZS
IC.FRM.RSDV.ZS
IC.FRM.THEV.ZS
IC.FRM.TRNG.ZS
IC.GOV.DURS.ZS
IC.IMP.CSBC.CD
IC.IMP.CSDC.CD
IC.IMP.TMBC
IC.IMP.TMDC
IC.ISV.DURS
IC.LGL.CRED.XQ
IC.LGL.DURS
IC.PRP.DURS
IC.PRP.PROC
IC.REG.COST.PC.FE.ZS
IC.REG.COST.PC.MA.ZS
IC.REG.COST.PC.ZS
IC.REG.DURS
IC.REG.DURS.FE
IC.REG.DURS.MA
IC.REG.PROC
IC.REG.PROC.FE
IC.REG.PROC.MA
IC.TAX.DURS
IC.TAX.GIFT.ZS
IC.TAX.LABR.CP.ZS
IC.TAX.METG
IC.TAX.OTHR.CP.ZS
IC.TAX.PAYM
IC.TAX.PRFT.CP.ZS
IC.TAX.TOTL.CP.ZS
IC.WRH.DURS
IC.WRH.PROC
IE.PPI.ENGY.CD
IE.PPI.ICTI.CD
IE.PPI.TRAN.CD
IE.PPI.WATR.CD
IE.PPN.ENGY.CD
IE.PPN.ICTI.CD
IE.PPN.TRAN.CD
IE.PPN.WATR.CD
IP.IDS.NRCT
IP.IDS.RSCT
IP.JRN.ARTC.SC
IP.PAT.NRES
IP.PAT.RESD
IP.TMK.NRCT
IP.TMK.RSCT
IQ.CPA.BREG.XQ
IQ.CPA.DEBT.XQ
IQ.CPA.ECON.XQ
IQ.CPA.ENVR.XQ
IQ.CPA.FINQ.XQ
IQ.CPA.FINS.XQ
IQ.CPA.FISP.XQ
IQ.CPA.GNDR.XQ
IQ.CPA.HRES.XQ
IQ.CPA.IRAI.XQ
IQ.CPA.MACR.XQ
IQ.CPA.PADM.XQ
IQ.CPA.PRES.XQ
IQ.CPA.PROP.XQ
IQ.CPA.PROT.XQ
IQ.CPA.PUBS.XQ
IQ.CPA.REVN.XQ
IQ.CPA.SOCI.XQ
IQ.CPA.STRC.XQ
IQ.CPA.TRAD.XQ
IQ.CPA.TRAN.XQ
IQ.SCI.MTHD
IQ.SCI.OVRL
IQ.SCI.PRDC
IQ.SCI.SRCE
IQ.SPI.OVRL
IQ.SPI.PIL1
IQ.SPI.PIL2
IQ.SPI.PIL3
IQ.SPI.PIL4
IQ.SPI.PIL5
IS.AIR.DPRT
IS.AIR.GOOD.MT.K1
IS.AIR.PSGR
IS.RRS.GOOD.MT.K6
IS.RRS.PASG.KM
IS.RRS.TOTL.KM
IS.SHP.GCNW.XQ
IS.SHP.GOOD.TU
IT.CEL.SETS
IT.CEL.SETS.P2
IT.MLT.MAIN
IT.MLT.MAIN.P2
IT.NET.BBND
IT.NET.BBND.P2
IT.NET.SECR
IT.NET.SECR.P6
IT.NET.USER.ZS
LP.EXP.DURS.MD
LP.IMP.DURS.MD
LP.LPI.CUST.XQ
LP.LPI.INFR.XQ
LP.LPI.ITRN.XQ
LP.LPI.LOGS.XQ
LP.LPI.OVRL.XQ
LP.LPI.TIME.XQ
LP.LPI.TRAC.XQ
MS.MIL.MPRT.KD
MS.MIL.TOTL.P1
MS.MIL.TOTL.TF.ZS
MS.MIL.XPND.CD
MS.MIL.XPND.CN
MS.MIL.XPND.GD.ZS
MS.MIL.XPND.ZS
MS.MIL.XPRT.KD
NE.CON.GOVT.CD
NE.CON.GOVT.CN
NE.CON.GOVT.KD
NE.CON.GOVT.KD.ZG
NE.CON.GOVT.KN
NE.CON.GOVT.ZS
NE.CON.PRVT.CD
NE.CON.PRVT.CN
NE.CON.PRVT.CN.AD
NE.CON.PRVT.KD
NE.CON.PRVT.KD.ZG
NE.CON.PRVT.KN
NE.CON.PRVT.PC.KD
NE.CON.PRVT.PC.KD.ZG
NE.CON.PRVT.PP.CD
NE.CON.PRVT.PP.KD
NE.CON.PRVT.ZS
NE.CON.TOTL.CD
NE.CON.TOTL.CN
NE.CON.TOTL.KD
NE.CON.TOTL.KD.ZG
NE.CON.TOTL.KN
NE.CON.TOTL.ZS
NE.DAB.DEFL.ZS
NE.DAB.TOTL.CD
NE.DAB.TOTL.CN
NE.DAB.TOTL.KD
NE.DAB.TOTL.KN
NE.DAB.TOTL.ZS
NE.EXP.GNFS.CD
NE.EXP.GNFS.CN
NE.EXP.GNFS.KD
NE.EXP.GNFS.KD.ZG
NE.EXP.GNFS.KN
NE.EXP.GNFS.ZS
NE.GDI.FPRV.CN
NE.GDI.FPRV.ZS
NE.GDI.FTOT.CD
NE.GDI.FTOT.CN
NE.GDI.FTOT.KD
NE.GDI.FTOT.KD.ZG
NE.GDI.FTOT.KN
NE.GDI.FTOT.ZS
NE.GDI.STKB.CD
NE.GDI.STKB.CN
NE.GDI.STKB.KN
NE.GDI.TOTL.CD
NE.GDI.TOTL.CN
NE.GDI.TOTL.KD
NE.GDI.TOTL.KD.ZG
NE.GDI.TOTL.KN
NE.GDI.TOTL.ZS
NE.IMP.GNFS.CD
NE.IMP.GNFS.CN
NE.IMP.GNFS.KD
NE.IMP.GNFS.KD.ZG
NE.IMP.GNFS.KN
NE.IMP.GNFS.ZS
NE.RSB.GNFS.CD
NE.RSB.GNFS.CN
NE.RSB.GNFS.KN
NE.RSB.GNFS.ZS
NE.TRD.GNFS.ZS
NV.AGR.EMPL.KD
NV.AGR.TOTL.CD
NV.AGR.TOTL.CN
NV.AGR.TOTL.KD
NV.AGR.TOTL.KD.ZG
NV.AGR.TOTL.KN
NV.AGR.TOTL.ZS
NV.FSM.TOTL.CN
NV.FSM.TOTL.KN
NV.IND.EMPL.KD
NV.IND.MANF.CD
NV.IND.MANF.CN
NV.IND.MANF.KD
NV.IND.MANF.KD.ZG
NV.IND.MANF.KN
NV.IND.MANF.ZS
NV.IND.TOTL.CD
NV.IND.TOTL.CN
NV.IND.TOTL.KD
NV.IND.TOTL.KD.ZG
NV.IND.TOTL.KN
NV.IND.TOTL.ZS
NV.MNF.CHEM.ZS.UN
NV.MNF.FBTO.ZS.UN
NV.MNF.MTRN.ZS.UN
NV.MNF.OTHR.ZS.UN
NV.MNF.TECH.ZS.UN
NV.MNF.TXTL.ZS.UN
NV.SRV.EMPL.KD
NV.SRV.TOTL.CD
NV.SRV.TOTL.CN
NV.SRV.TOTL.KD
NV.SRV.TOTL.KD.ZG
NV.SRV.TOTL.KN
NV.SRV.TOTL.ZS
NY.ADJ.AEDU.CD
NY.ADJ.AEDU.GN.ZS
NY.ADJ.DCO2.CD
NY.ADJ.DCO2.GN.ZS
NY.ADJ.DFOR.CD
NY.ADJ.DFOR.GN.ZS
NY.ADJ.DKAP.CD
NY.ADJ.DKAP.GN.ZS
NY.ADJ.DMIN.CD
NY.ADJ.DMIN.GN.ZS
NY.ADJ.DNGY.CD
NY.ADJ.DNGY.GN.ZS
NY.ADJ.DPEM.CD
NY.ADJ.DPEM.GN.ZS
NY.ADJ.DRES.GN.ZS
NY.ADJ.ICTR.GN.ZS
NY.ADJ.NNAT.CD
NY.ADJ.NNAT.GN.ZS
NY.ADJ.NNTY.CD
NY.ADJ.NNTY.KD
NY.ADJ.NNTY.KD.ZG
NY.ADJ.NNTY.PC.CD
NY.ADJ.NNTY.PC.KD
NY.ADJ.NNTY.PC.KD.ZG
NY.ADJ.SVNG.CD
NY.ADJ.SVNG.GN.ZS
NY.ADJ.SVNX.CD
NY.ADJ.SVNX.GN.ZS
NY.EXP.CAPM.KN
NY.GDP.COAL.RT.ZS
NY.GDP.DEFL.KD.ZG
NY.GDP.DEFL.KD.ZG.AD
NY.GDP.DEFL.ZS
NY.GDP.DEFL.ZS.AD
NY.GDP.DISC.CN
NY.GDP.DISC.KN
NY.GDP.FCST.CD
NY.GDP.FCST.CN
NY.GDP.FCST.KD
NY.GDP.FCST.KN
NY.GDP.FRST.RT.ZS
NY.GDP.MINR.RT.ZS
NY.GDP.MKTP.CD
NY.GDP.MKTP.CN
NY.GDP.MKTP.CN.AD
NY.GDP.MKTP.KD
NY.GDP.MKTP.KD.ZG
NY.GDP.MKTP.KN
NY.GDP.MKTP.PP.CD
NY.GDP.MKTP.PP.KD
NY.GDP.NGAS.RT.ZS
NY.GDP.PCAP.CD
NY.GDP.PCAP.CN
NY.GDP.PCAP.KD
NY.GDP.PCAP.KD.ZG
NY.GDP.PCAP.KN
NY.GDP.PCAP.PP.CD
NY.GDP.PCAP.PP.KD
NY.GDP.PETR.RT.ZS
NY.GDP.TOTL.RT.ZS
NY.GDS.TOTL.CD
NY.GDS.TOTL.CN
NY.GDS.TOTL.ZS
NY.GDY.TOTL.KN
NY.GNP.ATLS.CD
NY.GNP.MKTP.CD
NY.GNP.MKTP.CN
NY.GNP.MKTP.CN.AD
NY.GNP.MKTP.KD
NY.GNP.MKTP.KD.ZG
NY.GNP.MKTP.KN
NY.GNP.MKTP.PP.CD
NY.GNP.MKTP.PP.KD
NY.GNP.PCAP.CD
NY.GNP.PCAP.CN
NY.GNP.PCAP.KD
NY.GNP.PCAP.KD.ZG
NY.GNP.PCAP.KN
NY.GNP.PCAP.PP.CD
NY.GNP.PCAP.PP.KD
NY.GNS.ICTR.CD
NY.GNS.ICTR.CN
NY.GNS.ICTR.GN.ZS
NY.GNS.ICTR.ZS
NY.GSR.NFCY.CD
NY.GSR.NFCY.CN
NY.GSR.NFCY.KN
NY.TAX.NIND.CD
NY.TAX.NIND.CN
NY.TAX.NIND.KN
NY.TRF.NCTR.CD
NY.TRF.NCTR.CN
NY.TRF.NCTR.KN
NY.TTF.GNFS.KN
PA.NUS.ATLS
PA.NUS.FCRF
PA.NUS.PPP
PA.NUS.PPPC.RF
PA.NUS.PRVT.PP
per_allsp.adq_pop_tot
per_allsp.ben_q1_tot
per_allsp.cov_pop_tot
per_lm_alllm.adq_pop_tot
per_lm_alllm.ben_q1_tot
per_lm_alllm.cov_pop_tot
per_lm_alllm.cov_q1_tot
per_lm_alllm.cov_q2_tot
per_lm_alllm.cov_q3_tot
per_lm_alllm.cov_q4_tot
per_lm_alllm.cov_q5_tot
per_sa_allsa.adq_pop_tot
per_sa_allsa.ben_q1_tot
per_sa_allsa.cov_pop_tot
per_sa_allsa.cov_q1_tot
per_sa_allsa.cov_q2_tot
per_sa_allsa.cov_q3_tot
per_sa_allsa.cov_q4_tot
per_sa_allsa.cov_q5_tot
per_si_allsi.adq_pop_tot
per_si_allsi.ben_q1_tot
per_si_allsi.cov_pop_tot
per_si_allsi.cov_q1_tot
per_si_allsi.cov_q2_tot
per_si_allsi.cov_q3_tot
per_si_allsi.cov_q4_tot
per_si_allsi.cov_q5_tot
PX.REX.REER
SE.ADT.1524.LT.FE.ZS
SE.ADT.1524.LT.FM.ZS
SE.ADT.1524.LT.MA.ZS
SE.ADT.1524.LT.ZS
SE.ADT.LITR.FE.ZS
SE.ADT.LITR.MA.ZS
SE.ADT.LITR.ZS
SE.COM.DURS
SE.ENR.PRIM.FM.ZS
SE.ENR.PRSC.FM.ZS
SE.ENR.SECO.FM.ZS
SE.ENR.TERT.FM.ZS
SE.PRE.DURS
SE.PRE.ENRL.TC.ZS
SE.PRE.ENRR
SE.PRE.ENRR.FE
SE.PRE.ENRR.MA
SE.PRE.TCAQ.FE.ZS
SE.PRE.TCAQ.MA.ZS
SE.PRE.TCAQ.ZS
SE.PRM.AGES
SE.PRM.CMPT.FE.ZS
SE.PRM.CMPT.MA.ZS
SE.PRM.CMPT.ZS
SE.PRM.CUAT.FE.ZS
SE.PRM.CUAT.MA.ZS
SE.PRM.CUAT.ZS
SE.PRM.DURS
SE.PRM.ENRL
SE.PRM.ENRL.FE.ZS
SE.PRM.ENRL.TC.ZS
SE.PRM.ENRR
SE.PRM.ENRR.FE
SE.PRM.ENRR.MA
SE.PRM.GINT.FE.ZS
SE.PRM.GINT.MA.ZS
SE.PRM.GINT.ZS
SE.PRM.NENR
SE.PRM.NENR.FE
SE.PRM.NENR.MA
SE.PRM.NINT.FE.ZS
SE.PRM.NINT.MA.ZS
SE.PRM.NINT.ZS
SE.PRM.OENR.FE.ZS
SE.PRM.OENR.MA.ZS
SE.PRM.OENR.ZS
SE.PRM.PRIV.ZS
SE.PRM.PRS5.FE.ZS
SE.PRM.PRS5.MA.ZS
SE.PRM.PRS5.ZS
SE.PRM.PRSL.FE.ZS
SE.PRM.PRSL.MA.ZS
SE.PRM.PRSL.ZS
SE.PRM.REPT.FE.ZS
SE.PRM.REPT.MA.ZS
SE.PRM.REPT.ZS
SE.PRM.TCAQ.FE.ZS
SE.PRM.TCAQ.MA.ZS
SE.PRM.TCAQ.ZS
SE.PRM.TCHR
SE.PRM.TCHR.FE.ZS
SE.PRM.TENR
SE.PRM.TENR.FE
SE.PRM.TENR.MA
SE.PRM.UNER
SE.PRM.UNER.FE
SE.PRM.UNER.FE.ZS
SE.PRM.UNER.MA
SE.PRM.UNER.MA.ZS
SE.PRM.UNER.ZS
SE.SEC.AGES
SE.SEC.CMPT.LO.FE.ZS
SE.SEC.CMPT.LO.MA.ZS
SE.SEC.CMPT.LO.ZS
SE.SEC.CUAT.LO.FE.ZS
SE.SEC.CUAT.LO.MA.ZS
SE.SEC.CUAT.LO.ZS
SE.SEC.CUAT.PO.FE.ZS
SE.SEC.CUAT.PO.MA.ZS
SE.SEC.CUAT.PO.ZS
SE.SEC.CUAT.UP.FE.ZS
SE.SEC.CUAT.UP.MA.ZS
SE.SEC.CUAT.UP.ZS
SE.SEC.DURS
SE.SEC.ENRL
SE.SEC.ENRL.FE.ZS
SE.SEC.ENRL.GC
SE.SEC.ENRL.GC.FE.ZS
SE.SEC.ENRL.LO.TC.ZS
SE.SEC.ENRL.TC.ZS
SE.SEC.ENRL.UP.TC.ZS
SE.SEC.ENRL.VO
SE.SEC.ENRL.VO.FE.ZS
SE.SEC.ENRR
SE.SEC.ENRR.FE
SE.SEC.ENRR.MA
SE.SEC.NENR
SE.SEC.NENR.FE
SE.SEC.NENR.MA
SE.SEC.PRIV.ZS
SE.SEC.PROG.FE.ZS
SE.SEC.PROG.MA.ZS
SE.SEC.PROG.ZS
SE.SEC.TCAQ.FE.ZS
SE.SEC.TCAQ.LO.FE.ZS
SE.SEC.TCAQ.LO.MA.ZS
SE.SEC.TCAQ.LO.ZS
SE.SEC.TCAQ.MA.ZS
SE.SEC.TCAQ.UP.FE.ZS
SE.SEC.TCAQ.UP.MA.ZS
SE.SEC.TCAQ.UP.ZS
SE.SEC.TCAQ.ZS
SE.SEC.TCHR
SE.SEC.TCHR.FE
SE.SEC.TCHR.FE.ZS
SE.SEC.UNER.LO.FE.ZS
SE.SEC.UNER.LO.MA.ZS
SE.SEC.UNER.LO.ZS
SE.TER.CUAT.BA.FE.ZS
SE.TER.CUAT.BA.MA.ZS
SE.TER.CUAT.BA.ZS
SE.TER.CUAT.DO.FE.ZS
SE.TER.CUAT.DO.MA.ZS
SE.TER.CUAT.DO.ZS
SE.TER.CUAT.MS.FE.ZS
SE.TER.CUAT.MS.MA.ZS
SE.TER.CUAT.MS.ZS
SE.TER.CUAT.ST.FE.ZS
SE.TER.CUAT.ST.MA.ZS
SE.TER.CUAT.ST.ZS
SE.TER.ENRL.TC.ZS
SE.TER.ENRR
SE.TER.ENRR.FE
SE.TER.ENRR.MA
SE.TER.TCHR.FE.ZS
SE.XPD.CPRM.ZS
SE.XPD.CSEC.ZS
SE.XPD.CTER.ZS
SE.XPD.CTOT.ZS
SE.XPD.PRIM.PC.ZS
SE.XPD.PRIM.ZS
SE.XPD.SECO.PC.ZS
SE.XPD.SECO.ZS
SE.XPD.TERT.PC.ZS
SE.XPD.TERT.ZS
SE.XPD.TOTL.GB.ZS
SE.XPD.TOTL.GD.ZS
SG.DMK.ALLD.FN.ZS
SG.DMK.SRCR.FN.ZS
SG.GEN.PARL.ZS
SG.LAW.INDX
SG.TIM.UWRK.FE
SG.TIM.UWRK.MA
SG.VAW.1549.ZS
SG.VAW.ARGU.ZS
SG.VAW.BURN.ZS
SG.VAW.GOES.ZS
SG.VAW.NEGL.ZS
SG.VAW.REAS.ZS
SG.VAW.REFU.ZS
SH.ALC.PCAP.FE.LI
SH.ALC.PCAP.LI
SH.ALC.PCAP.MA.LI
SH.ANM.ALLW.ZS
SH.ANM.CHLD.ZS
SH.ANM.NPRG.ZS
SH.CON.1524.FE.ZS
SH.CON.1524.MA.ZS
SH.DTH.0509
SH.DTH.1014
SH.DTH.1519
SH.DTH.2024
SH.DTH.COMM.ZS
SH.DTH.IMRT
SH.DTH.INJR.ZS
SH.DTH.MORT
SH.DTH.NCOM.ZS
SH.DTH.NMRT
SH.DYN.0509
SH.DYN.1014
SH.DYN.1519
SH.DYN.2024
SH.DYN.AIDS.FE.ZS
SH.DYN.AIDS.ZS
SH.DYN.MORT
SH.DYN.MORT.FE
SH.DYN.MORT.MA
SH.DYN.NCOM.FE.ZS
SH.DYN.NCOM.MA.ZS
SH.DYN.NCOM.ZS
SH.DYN.NMRT
SH.FPL.SATM.ZS
SH.H2O.BASW.RU.ZS
SH.H2O.BASW.UR.ZS
SH.H2O.BASW.ZS
SH.H2O.SMDW.RU.ZS
SH.H2O.SMDW.UR.ZS
SH.H2O.SMDW.ZS
SH.HIV.0014
SH.HIV.1524.FE.ZS
SH.HIV.1524.MA.ZS
SH.HIV.ARTC.ZS
SH.HIV.INCD
SH.HIV.INCD.14
SH.HIV.INCD.TL
SH.HIV.INCD.TL.P3
SH.HIV.INCD.YG
SH.HIV.INCD.YG.P3
SH.HIV.INCD.ZS
SH.HIV.PMTC.ZS
SH.IMM.HEPB
SH.IMM.IDPT
SH.IMM.MEAS
SH.MED.BEDS.ZS
SH.MED.CMHW.P3
SH.MED.NUMW.P3
SH.MED.PHYS.ZS
SH.MED.SAOP.P5
SH.MLR.INCD.P3
SH.MLR.NETS.ZS
SH.MLR.TRET.ZS
SH.MMR.DTHS
SH.MMR.RISK
SH.MMR.RISK.ZS
SH.PRG.ANEM
SH.PRV.SMOK
SH.PRV.SMOK.FE
SH.PRV.SMOK.MA
SH.SGR.CRSK.ZS
SH.SGR.IRSK.ZS
SH.SGR.PROC.P5
SH.STA.AIRP.FE.P5
SH.STA.AIRP.MA.P5
SH.STA.AIRP.P5
SH.STA.ANVC.ZS
SH.STA.ARIC.ZS
SH.STA.BASS.RU.ZS
SH.STA.BASS.UR.ZS
SH.STA.BASS.ZS
SH.STA.BFED.ZS
SH.STA.BRTC.ZS
SH.STA.BRTW.ZS
SH.STA.DIAB.ZS
SH.STA.FGMS.ZS
SH.STA.HYGN.RU.ZS
SH.STA.HYGN.UR.ZS
SH.STA.HYGN.ZS
SH.STA.MALN.FE.ZS
SH.STA.MALN.MA.ZS
SH.STA.MALN.ZS
SH.STA.MMRT
SH.STA.MMRT.NE
SH.STA.ODFC.RU.ZS
SH.STA.ODFC.UR.ZS
SH.STA.ODFC.ZS
SH.STA.ORCF.ZS
SH.STA.ORTH
SH.STA.OWGH.FE.ZS
SH.STA.OWGH.MA.ZS
SH.STA.OWGH.ME.ZS
SH.STA.OWGH.ZS
SH.STA.POIS.P5
SH.STA.POIS.P5.FE
SH.STA.POIS.P5.MA
SH.STA.SMSS.RU.ZS
SH.STA.SMSS.UR.ZS
SH.STA.SMSS.ZS
SH.STA.STNT.FE.ZS
SH.STA.STNT.MA.ZS
SH.STA.STNT.ME.ZS
SH.STA.STNT.ZS
SH.STA.SUIC.FE.P5
SH.STA.SUIC.MA.P5
SH.STA.SUIC.P5
SH.STA.TRAF.P5
SH.STA.WASH.P5
SH.STA.WAST.FE.ZS
SH.STA.WAST.MA.ZS
SH.STA.WAST.ZS
SH.SVR.WAST.FE.ZS
SH.SVR.WAST.MA.ZS
SH.SVR.WAST.ZS
SH.TBS.CURE.ZS
SH.TBS.DTEC.ZS
SH.TBS.INCD
SH.UHC.NOP1.CG
SH.UHC.NOP1.TO
SH.UHC.NOP1.ZG
SH.UHC.NOP1.ZS
SH.UHC.NOP2.CG
SH.UHC.NOP2.TO
SH.UHC.NOP2.ZG
SH.UHC.NOP2.ZS
SH.UHC.OOPC.10.TO
SH.UHC.OOPC.10.ZS
SH.UHC.OOPC.25.TO
SH.UHC.OOPC.25.ZS
SH.UHC.SRVS.CV.XD
SH.VAC.TTNS.ZS
SH.XPD.CHEX.GD.ZS
SH.XPD.CHEX.PC.CD
SH.XPD.CHEX.PP.CD
SH.XPD.EHEX.CH.ZS
SH.XPD.EHEX.PC.CD
SH.XPD.EHEX.PP.CD
SH.XPD.GHED.CH.ZS
SH.XPD.GHED.GD.ZS
SH.XPD.GHED.GE.ZS
SH.XPD.GHED.PC.CD
SH.XPD.GHED.PP.CD
SH.XPD.OOPC.CH.ZS
SH.XPD.OOPC.PC.CD
SH.XPD.OOPC.PP.CD
SH.XPD.PVTD.CH.ZS
SH.XPD.PVTD.PC.CD
SH.XPD.PVTD.PP.CD
SI.DST.02ND.20
SI.DST.03RD.20
SI.DST.04TH.20
SI.DST.05TH.20
SI.DST.10TH.10
SI.DST.50MD
SI.DST.FRST.10
SI.DST.FRST.20
SI.POV.DDAY
SI.POV.GAPS
SI.POV.GINI
SI.POV.LMIC
SI.POV.LMIC.GP
SI.POV.MDIM
SI.POV.MDIM.17
SI.POV.MDIM.17.XQ
SI.POV.MDIM.FE
SI.POV.MDIM.HH
SI.POV.MDIM.IT
SI.POV.MDIM.MA
SI.POV.MDIM.XQ
SI.POV.NAHC
SI.POV.UMIC
SI.POV.UMIC.GP
SI.RMT.COST.IB.ZS
SI.RMT.COST.OB.ZS
SI.SPR.PC40
SI.SPR.PC40.ZG
SI.SPR.PCAP
SI.SPR.PCAP.ZG
SL.AGR.0714.FE.ZS
SL.AGR.0714.MA.ZS
SL.AGR.0714.ZS
SL.AGR.EMPL.FE.ZS
SL.AGR.EMPL.MA.ZS
SL.AGR.EMPL.ZS
SL.EMP.1524.SP.FE.NE.ZS
SL.EMP.1524.SP.FE.ZS
SL.EMP.1524.SP.MA.NE.ZS
SL.EMP.1524.SP.MA.ZS
SL.EMP.1524.SP.NE.ZS
SL.EMP.1524.SP.ZS
SL.EMP.MPYR.FE.ZS
SL.EMP.MPYR.MA.ZS
SL.EMP.MPYR.ZS
SL.EMP.SELF.FE.ZS
SL.EMP.SELF.MA.ZS
SL.EMP.SELF.ZS
SL.EMP.SMGT.FE.ZS
SL.EMP.TOTL.SP.FE.NE.ZS
SL.EMP.TOTL.SP.FE.ZS
SL.EMP.TOTL.SP.MA.NE.ZS
SL.EMP.TOTL.SP.MA.ZS
SL.EMP.TOTL.SP.NE.ZS
SL.EMP.TOTL.SP.ZS
SL.EMP.VULN.FE.ZS
SL.EMP.VULN.MA.ZS
SL.EMP.VULN.ZS
SL.EMP.WORK.FE.ZS
SL.EMP.WORK.MA.ZS
SL.EMP.WORK.ZS
SL.FAM.0714.FE.ZS
SL.FAM.0714.MA.ZS
SL.FAM.0714.ZS
SL.FAM.WORK.FE.ZS
SL.FAM.WORK.MA.ZS
SL.FAM.WORK.ZS
SL.GDP.PCAP.EM.KD
SL.IND.EMPL.FE.ZS
SL.IND.EMPL.MA.ZS
SL.IND.EMPL.ZS
SL.MNF.0714.FE.ZS
SL.MNF.0714.MA.ZS
SL.MNF.0714.ZS
SL.SLF.0714.FE.ZS
SL.SLF.0714.MA.ZS
SL.SLF.0714.ZS
SL.SRV.0714.FE.ZS
SL.SRV.0714.MA.ZS
SL.SRV.0714.ZS
SL.SRV.EMPL.FE.ZS
SL.SRV.EMPL.MA.ZS
SL.SRV.EMPL.ZS
SL.TLF.0714.FE.ZS
SL.TLF.0714.MA.ZS
SL.TLF.0714.SW.FE.TM
SL.TLF.0714.SW.FE.ZS
SL.TLF.0714.SW.MA.TM
SL.TLF.0714.SW.MA.ZS
SL.TLF.0714.SW.TM
SL.TLF.0714.SW.ZS
SL.TLF.0714.WK.FE.TM
SL.TLF.0714.WK.FE.ZS
SL.TLF.0714.WK.MA.TM
SL.TLF.0714.WK.MA.ZS
SL.TLF.0714.WK.TM
SL.TLF.0714.WK.ZS
SL.TLF.0714.ZS
SL.TLF.ACTI.1524.FE.NE.ZS
SL.TLF.ACTI.1524.FE.ZS
SL.TLF.ACTI.1524.MA.NE.ZS
SL.TLF.ACTI.1524.MA.ZS
SL.TLF.ACTI.1524.NE.ZS
SL.TLF.ACTI.1524.ZS
SL.TLF.ACTI.FE.ZS
SL.TLF.ACTI.MA.ZS
SL.TLF.ACTI.ZS
SL.TLF.ADVN.FE.ZS
SL.TLF.ADVN.MA.ZS
SL.TLF.ADVN.ZS
SL.TLF.BASC.FE.ZS
SL.TLF.BASC.MA.ZS
SL.TLF.BASC.ZS
SL.TLF.CACT.FE.NE.ZS
SL.TLF.CACT.FE.ZS
SL.TLF.CACT.FM.NE.ZS
SL.TLF.CACT.FM.ZS
SL.TLF.CACT.MA.NE.ZS
SL.TLF.CACT.MA.ZS
SL.TLF.CACT.NE.ZS
SL.TLF.CACT.ZS
SL.TLF.INTM.FE.ZS
SL.TLF.INTM.MA.ZS
SL.TLF.INTM.ZS
SL.TLF.PART.FE.ZS
SL.TLF.PART.MA.ZS
SL.TLF.PART.ZS
SL.TLF.TOTL.FE.ZS
SL.TLF.TOTL.IN
SL.UEM.1524.FE.NE.ZS
SL.UEM.1524.FE.ZS
SL.UEM.1524.MA.NE.ZS
SL.UEM.1524.MA.ZS
SL.UEM.1524.NE.ZS
SL.UEM.1524.ZS
SL.UEM.ADVN.FE.ZS
SL.UEM.ADVN.MA.ZS
SL.UEM.ADVN.ZS
SL.UEM.BASC.FE.ZS
SL.UEM.BASC.MA.ZS
SL.UEM.BASC.ZS
SL.UEM.INTM.FE.ZS
SL.UEM.INTM.MA.ZS
SL.UEM.INTM.ZS
SL.UEM.NEET.FE.ZS
SL.UEM.NEET.MA.ZS
SL.UEM.NEET.ZS
SL.UEM.TOTL.FE.NE.ZS
SL.UEM.TOTL.FE.ZS
SL.UEM.TOTL.MA.NE.ZS
SL.UEM.TOTL.MA.ZS
SL.UEM.TOTL.NE.ZS
SL.UEM.TOTL.ZS

SP.URB.TOTL
SP.URB.TOTL.IN.ZS
SP.UWT.TFRT
ST.INT.ARVL
ST.INT.DPRT
ST.INT.RCPT.CD
ST.INT.RCPT.XP.ZS
ST.INT.TRNR.CD
ST.INT.TRNX.CD
ST.INT.TVLR.CD
ST.INT.TVLX.CD
ST.INT.XPND.CD
ST.INT.XPND.MP.ZS
TG.VAL.TOTL.GD.ZS
TM.QTY.MRCH.XD.WD
TM.TAX.MANF.BC.ZS
TM.TAX.MANF.BR.ZS
TM.TAX.MANF.IP.ZS
TM.TAX.MANF.SM.AR.ZS
TM.TAX.MANF.SM.FN.ZS
TM.TAX.MANF.SR.ZS
TM.TAX.MANF.WM.AR.ZS
TM.TAX.MANF.WM.FN.ZS
TM.TAX.MRCH.BC.ZS
TM.TAX.MRCH.BR.ZS
TM.TAX.MRCH.IP.ZS
TM.TAX.MRCH.SM.AR.ZS
TM.TAX.MRCH.SM.FN.ZS
TM.TAX.MRCH.SR.ZS
TM.TAX.MRCH.WM.AR.ZS
TM.TAX.MRCH.WM.FN.ZS
TM.TAX.TCOM.BC.ZS
TM.TAX.TCOM.BR.ZS
TM.TAX.TCOM.IP.ZS
TM.TAX.TCOM.SM.AR.ZS
TM.TAX.TCOM.SM.FN.ZS
TM.TAX.TCOM.SR.ZS
TM.TAX.TCOM.WM.AR.ZS
TM.TAX.TCOM.WM.FN.ZS
TM.UVI.MRCH.XD.WD
TM.VAL.AGRI.ZS.UN
TM.VAL.FOOD.ZS.UN
TM.VAL.FUEL.ZS.UN
TM.VAL.ICTG.ZS.UN
TM.VAL.INSF.ZS.WT
TM.VAL.MANF.ZS.UN
TM.VAL.MMTL.ZS.UN
TM.VAL.MRCH.AL.ZS
TM.VAL.MRCH.CD.WT
TM.VAL.MRCH.HI.ZS
TM.VAL.MRCH.OR.ZS
TM.VAL.MRCH.R1.ZS
TM.VAL.MRCH.R2.ZS
TM.VAL.MRCH.R3.ZS
TM.VAL.MRCH.R4.ZS
TM.VAL.MRCH.R5.ZS
TM.VAL.MRCH.R6.ZS
TM.VAL.MRCH.RS.ZS
TM.VAL.MRCH.WL.CD
TM.VAL.MRCH.WR.ZS
TM.VAL.MRCH.XD.WD
TM.VAL.OTHR.ZS.WT
TM.VAL.SERV.CD.WT
TM.VAL.TRAN.ZS.WT
TM.VAL.TRVL.ZS.WT
TT.PRI.MRCH.XD.WD
TX.MNF.TECH.ZS.UN
TX.QTY.MRCH.XD.WD
TX.UVI.MRCH.XD.WD
TX.VAL.AGRI.ZS.UN
TX.VAL.FOOD.ZS.UN
TX.VAL.FUEL.ZS.UN
TX.VAL.ICTG.ZS.UN
TX.VAL.INSF.ZS.WT
TX.VAL.MANF.ZS.UN
TX.VAL.MMTL.ZS.UN
TX.VAL.MRCH.AL.ZS
TX.VAL.MRCH.CD.WT
TX.VAL.MRCH.HI.ZS
TX.VAL.MRCH.OR.ZS
TX.VAL.MRCH.R1.ZS
TX.VAL.MRCH.R2.ZS
TX.VAL.MRCH.R3.ZS
TX.VAL.MRCH.R4.ZS
TX.VAL.MRCH.R5.ZS
TX.VAL.MRCH.R6.ZS
TX.VAL.MRCH.RS.ZS
TX.VAL.MRCH.WL.CD
TX.VAL.MRCH.WR.ZS
TX.VAL.MRCH.XD.WD
TX.VAL.OTHR.ZS.WT
TX.VAL.SERV.CD.WT
TX.VAL.TECH.CD
TX.VAL.TECH.MF.ZS
TX.VAL.TRAN.ZS.WT
TX.VAL.TRVL.ZS.WT
VC.BTL.DETH
VC.IDP.NWCV
VC.IDP.NWDS
VC.IDP.TOCV
VC.IHR.PSRC.FE.P5
VC.IHR.PSRC.MA.P5
VC.IHR.PSRC.P5
CPU times: user 7min, sys: 54.9 s, total: 7min 55s
Wall time: 59min 19s

# Resave dict verion of coverage for easier use

In [3]:
with open('all_wb_indicators.pickle', 'rb') as handle:
    coverage = pkl.load(handle)

In [4]:
coverage

[['AG.AGR.TRAC.NO',
  {'id': 'AG.AGR.TRAC.NO', 'value': 'Agricultural machinery, tractors'},
  0.8589743589743589,
  0.0,
      economy  YR1960    YR1961    YR1962    YR1963    YR1964    YR1965  \
  0       ABW     NaN       NaN       NaN       NaN       NaN       NaN
  1       AFE     NaN  169776.0  176648.0  180067.0  185072.0  191771.0
  2       AFG     NaN     120.0     150.0     200.0     200.0     300.0
  3       AFW     NaN    2733.0    3772.0    4577.0    5404.0    6364.0
  4       AGO     NaN     800.0    1645.0    2000.0    2817.0    3000.0
  ..      ...     ...       ...       ...       ...       ...       ...
  261     XKX     NaN       NaN       NaN       NaN       NaN       NaN
  262     YEM     NaN     380.0     440.0     510.0     700.0     910.0
  263     ZAF     NaN  122218.0  126923.0  130000.0  133552.0  138422.0
  264     ZMB     NaN    2435.0    2760.0    2000.0    1600.0    1600.0
  265     ZWE     NaN   12567.0   12860.0   13000.0   13300.0   13600.0

         YR1966    YR1967    YR1968  ...  YR2012  YR2013  YR2014  YR2015  \
  0         NaN       NaN       NaN  ...     NaN     NaN     NaN     NaN
  1    198700.0  206634.0  209857.0  ...     NaN     NaN     NaN     NaN
  2       400.0     500.0     500.0  ...     NaN     NaN     NaN     NaN
  3      7205.0    7960.0    8640.0  ...     NaN     NaN     NaN     NaN
  4      3729.0    4500.0    5300.0  ...     NaN     NaN     NaN     NaN
  ..        ...       ...       ...  ...     ...     ...     ...     ...
  261       NaN       NaN       NaN  ...     NaN     NaN     NaN     NaN
  262    1120.0    1230.0    1400.0  ...     NaN     NaN     NaN     NaN
  263  142000.0  145936.0  147884.0  ...     NaN     NaN     NaN     NaN
  264    1800.0    2060.0    2249.0  ...     NaN     NaN     NaN     NaN
  265   13900.0   14200.0   14300.0  ...     NaN     NaN     NaN     NaN

       YR2016  YR2017  YR2018  YR2019  YR2020  YR2021
  0       NaN     NaN     NaN     NaN     NaN     NaN
  1       NaN     NaN     NaN     NaN     NaN     NaN
  2       NaN     NaN     NaN     NaN     NaN     NaN
  3       NaN     NaN     NaN     NaN     NaN     NaN
  4       NaN     NaN     NaN     NaN     NaN     NaN
  ..      ...     ...     ...     ...     ...     ...
  261     NaN     NaN     NaN     NaN     NaN     NaN
  262     NaN     NaN     NaN     NaN     NaN     NaN
  263     NaN     NaN     NaN     NaN     NaN     NaN
  264     NaN     NaN     NaN     NaN     NaN     NaN
  265     NaN     NaN     NaN     NaN     NaN     NaN

  [266 rows x 63 columns]],
 ['AG.CON.FERT.PT.ZS',
  {'id': 'AG.CON.FERT.PT.ZS',
   'value': 'Fertilizer consumption (% of fertilizer production)'},
  0.33974358974358976,
  0.3347457627118644,
      economy  YR1960      YR1961      YR1962      YR1963      YR1964  \
  0       ABW     NaN         NaN         NaN         NaN         NaN
  1       AFE     NaN  158.829085  146.989616  146.703323  170.154237
  2       AFG     NaN         NaN         NaN         NaN         NaN
  3       AFW     NaN         NaN         NaN         NaN         NaN
  4       AGO     NaN         NaN         NaN         NaN         NaN
  ..      ...     ...         ...         ...         ...         ...
  261     XKX     NaN         NaN         NaN         NaN         NaN
  262     YEM     NaN         NaN         NaN         NaN         NaN
  263     ZAF     NaN  137.098441  129.266704  128.260870  145.105485
  264     ZMB     NaN         NaN         NaN         NaN         NaN
  265     ZWE     NaN  376.272727  355.545455  320.666667  460.000000

           YR1965      YR1966      YR1967      YR1968  ...      YR2012  \
  0           NaN         NaN         NaN         NaN  ...         NaN
  1    167.498388  157.522165  119.564105  132.398307  ...  221.665181
  2           NaN         NaN         NaN         NaN  ...  114.088877
  3           NaN         NaN  623.537736  111.011687  ...  312.384113
  4           NaN         NaN         NaN         NaN  ...         NaN
  ..          ...         ...         ...         ...  ...         ...
  261         NaN         NaN         NaN         NaN  ...         NaN
  262         NaN         NaN         NaN         NaN  ...         NaN
  263  143.629191  134.984227  101.548054  119.612934  ...  158.041061
  264         NaN         NaN         NaN         NaN  ...         NaN
  265  375.000000  376.000000  330.196078  338.775510  ...  359.605911

           YR2013      YR2014      YR2015      YR2016      YR2017      YR2018  \
  0           NaN         NaN         NaN         NaN         NaN         NaN
  1    587.284429  503.229434  655.456426  707.732716  751.837003  650.561068
  2    220.576394  495.085918  648.396816  662.617347  986.802156  369.324810
  3    175.837278  174.209125  221.232768  165.181902  213.236088  193.950380
  4           NaN         NaN         NaN         NaN         NaN         NaN
  ..          ...         ...         ...         ...         ...         ...
  261         NaN         NaN         NaN         NaN         NaN         NaN
  262         NaN         NaN         NaN         NaN         NaN         NaN
  263  235.739232  184.784623  238.459100  203.555556  237.990196  191.384074
  264         NaN         NaN         NaN         NaN         NaN         NaN
  265  368.705036  349.491525  251.118211  944.202899  671.559633  623.474178

           YR2019      YR2020  YR2021
  0           NaN         NaN     NaN
  1    669.694871  695.915513     NaN
  2    535.594410  427.560193     NaN
  3    217.588276  204.520272     NaN
  4           NaN         NaN     NaN
  ..          ...         ...     ...
  261         NaN         NaN     NaN
  262         NaN         NaN     NaN
  263  191.384074  191.384074     NaN
  264         NaN         NaN     NaN
  265  623.474178  623.474178     NaN

  [266 rows x 63 columns]],
 ['AG.CON.FERT.ZS',
  {'id': 'AG.CON.FERT.ZS',
   'value': 'Fertilizer consumption (kilograms per hectare of arable land)'},
  0.6474358974358975,
  0.7033898305084746,
      economy  YR1960     YR1961     YR1962     YR1963     YR1964     YR1965  \
  0       ABW     NaN        NaN        NaN        NaN        NaN        NaN
  1       AFE     NaN        NaN        NaN        NaN        NaN        NaN
  2       AFG     NaN   0.143791   0.142857   0.141935   0.141026   0.141026
  3       AFW     NaN        NaN        NaN        NaN        NaN        NaN
  4       AGO     NaN   0.374532   0.370370   0.514706   0.763636   1.444043
  ..      ...     ...        ...        ...        ...        ...        ...
  261     XKX     NaN        NaN        NaN        NaN        NaN        NaN
  262     YEM     NaN        NaN        NaN        NaN        NaN        NaN
  263     ZAF     NaN  17.910083  21.580996  24.380165  28.304527  29.844262
  264     ZMB     NaN   4.001569   3.334639   3.552019   4.056132   4.224270
  265     ZWE     NaN  21.957560  20.211886  24.231738  33.906634  36.319613

          YR1966     YR1967     YR1968  ...     YR2012     YR2013     YR2014  \
  0          NaN        NaN        NaN  ...        NaN        NaN        NaN
  1          NaN  14.091360  14.795467  ...  19.063658  19.510062  20.495891
  2     0.191449   1.274860   1.912290  ...   2.377852   4.882714  10.166112
  3     0.949617   1.137461   1.013116  ...   9.435961   9.760486   9.832501
  4     1.857143   2.367491   2.657343  ...   8.876049   9.263957   9.259388
  ..         ...        ...        ...  ...        ...        ...        ...
  261        NaN        NaN        NaN  ...        NaN        NaN        NaN
  262   0.011450   0.015186   0.026475  ...  16.022575  30.376353  22.431848
  263  35.047915  38.656081  41.449252  ...  61.583333  67.500000  66.491667
  264   4.589917   5.538922   7.060998  ...  37.626097  48.972138  50.466858
  265  35.222482  38.535469  37.136465  ...  18.250000  25.625000  25.775000

          YR2015     YR2016     YR2017     YR2018     YR2019     YR2020  YR2021
  0          NaN        NaN        NaN        NaN        NaN        NaN     NaN
  1    19.815202  21.821774  25.064483  23.192851  23.799653  24.735266     NaN
  2    13.324492  13.680146  20.452529   7.561350  10.973909   8.714495     NaN
  3    10.771815  13.162501  17.059341  16.371883  17.707359  19.609304     NaN
  4     8.048335   7.241269  10.674682   7.930094   7.402000   8.598882     NaN
  ..         ...        ...        ...        ...        ...        ...     ...
  261        NaN        NaN        NaN        NaN        NaN        NaN     NaN
  262   1.794963  18.982424  12.732158   3.605039  10.572919  10.628964     NaN
  263  62.675000  57.250000  72.825000  63.491667  63.491667  63.491667     NaN
  264  55.910442  63.985558  72.052916  52.510934  67.575600  79.764039     NaN
  265  19.650000  32.575000  36.600000  33.200000  33.200000  33.200000     NaN

  [266 rows x 63 columns]],
 ['AG.LND.AGRI.K2',
  {'id': 'AG.LND.AGRI.K2', 'value': 'Agricultural land (sq. km)'},
  0.9038461538461539,
  0.8686440677966102,
      economy  YR1960     YR1961     YR1962     YR1963     YR1964     YR1965  \
  0       ABW     NaN       20.0       20.0       20.0       20.0       20.0
  1       AFE     NaN  6170422.2  6168162.2  6173452.2  6170802.2  6168292.2
  2       AFG     NaN   377000.0   377600.0   378100.0   378730.0   378750.0
  3       AFW     NaN  2980464.1  2990979.0  3014148.1  3025739.7  3049810.3
  4       AGO     NaN   451772.2   452072.2   452272.2   452572.2   452772.2
  ..      ...     ...        ...        ...        ...        ...        ...
  261     XKX     NaN        NaN        NaN        NaN        NaN        NaN
  262     YEM     NaN   233370.0   233480.0   233600.0   233700.0   233800.0
  263     ZAF     NaN  1013350.0  1001350.0   989950.0   977500.0   966100.0
  264     ZMB     NaN   193070.0   193600.0   194040.0   194590.0   195130.0
  265     ZWE     NaN   109850.0   110700.0   111550.0   112400.0   113050.0

          YR1966     YR1967     YR1968  ...       YR2012      YR2013  \
  0         20.0       20.0       20.0  ...       20.000       20.00
  1    6172092.2  6174062.2  6178902.2  ...  6441140.365  6461235.65
  2     379130.0   379790.0   379800.0  ...   379100.000   379100.00
  3    3048154.0  3045507.7  3054558.5  ...  3552415.200  3572750.10
  4     453072.2   453372.2   453672.2  ...   536221.240   541771.86
  ..         ...        ...        ...  ...          ...         ...
  261        NaN        NaN        NaN  ...          NaN         NaN
  262   233910.0   233980.0   234030.0  ...   235010.000   234990.00
  263   964240.0   961480.0   959270.0  ...   963410.000   963410.00
  264   196070.0   196610.0   197350.0  ...   238360.000   237360.00
  265   114100.0   114950.0   115800.0  ...   162000.000   162000.00

            YR2014     YR2015       YR2016      YR2017      YR2018      YR2019  \
  0         20.000       20.0       20.000       20.00       20.00       20.00
  1    6483468.675  6498087.9  6517235.025  6538552.75  6556857.12  6560796.62
  2     379100.000   379100.0   379100.000   379100.00   380100.00   380100.00
  3    3574968.500  3577363.4  3586105.221  3589797.00  3591824.60  3593420.60
  4     547322.480   552873.1   558423.800   563974.30   569524.90   569524.90
  ..           ...        ...          ...         ...         ...         ...
  261          NaN        NaN          NaN         NaN         NaN         NaN
  262   234516.000   234326.0   233858.000   234520.00   234520.00   234520.00
  263   963410.000   963410.0   963410.000   963410.00   963410.00   963410.00
  264   238360.000   238360.0   238360.000   238360.00   238360.00   238360.00
  265   162000.000   162000.0   162000.000   162000.00   162000.00   162000.00

           YR2020  YR2021
  0         20.00     NaN
  1    6568777.12     NaN
  2     383560.00     NaN
  3    3595031.00     NaN
  4     569524.90     NaN
  ..          ...     ...
  261         NaN     NaN
  262   234520.00     NaN
  263   963410.00     NaN
  264   238360.00     NaN
  265   162000.00     NaN

  [266 rows x 63 columns]],
 ['AG.LND.AGRI.ZS',
  {'id': 'AG.LND.AGRI.ZS', 'value': 'Agricultural land (% of land area)'},
  0.9038461538461539,
  0.8686440677966102,
      economy  YR1960     YR1961     YR1962     YR1963     YR1964     YR1965  \
  0       ABW     NaN  11.111111  11.111111  11.111111  11.111111  11.111111
  1       AFE     NaN  42.345505  42.329995  42.366298  42.348112  42.330887
  2       AFG     NaN  57.801696  57.893688  57.970348  58.066940  58.070006
  3       AFW     NaN  32.945755  33.061986  33.318095  33.446227  33.712301
  4       AGO     NaN  36.237443  36.261506  36.277549  36.301612  36.317655
  ..      ...     ...        ...        ...        ...        ...        ...
  261     XKX     NaN        NaN        NaN        NaN        NaN        NaN
  262     YEM     NaN  44.201375  44.222210  44.244938  44.263879  44.282819
  263     ZAF     NaN  83.534610  82.545401  81.605652  80.579347  79.639598
  264     ZMB     NaN  25.971563  26.042858  26.102046  26.176031  26.248672
  265     ZWE     NaN  28.396019  28.615743  28.835466  29.055189  29.223213

          YR1966     YR1967     YR1968  ...     YR2012     YR2013     YR2014  \
  0    11.111111  11.111111  11.111111  ...  11.111111  11.111111  11.111111
  1    42.356965  42.370485  42.403700  ...  43.388794  43.524271  43.674175
  2    58.128268  58.229459  58.230992  ...  58.123668  58.123668  58.123668
  3    33.693993  33.664741  33.764787  ...  39.271519  39.496319  39.520843
  4    36.341718  36.365782  36.389845  ...  43.011249  43.456474  43.901699
  ..         ...        ...        ...  ...        ...        ...        ...
  261        NaN        NaN        NaN  ...        NaN        NaN        NaN
  262  44.303654  44.316912  44.326382  ...  44.511999  44.508211  44.418433
  263  79.486271  79.258752  79.076573  ...  79.417850  79.417850  79.417850
  264  26.375119  26.447760  26.547304  ...  32.063923  31.929404  32.063923
  265  29.494636  29.714360  29.934083  ...  41.876696  41.876696  41.876696

          YR2015     YR2016     YR2017     YR2018     YR2019     YR2020  YR2021
  0    11.111111  11.111111  11.111111  11.111111  11.111111  11.111111     NaN
  1    43.772496  43.901452  44.045088  44.168345  44.194846  44.248721     NaN
  2    58.123668  58.123668  58.123668  58.276988  58.276988  58.807476     NaN
  3    39.547318  39.643958  39.684770  39.707185  39.724829  39.742662     NaN
  4    44.346924  44.792155  45.237371  45.682594  45.682594  45.682594     NaN
  ..         ...        ...        ...        ...        ...        ...     ...
  261        NaN        NaN        NaN        NaN        NaN        NaN     NaN
  262  44.382446  44.293805  44.419190  44.419190  44.419190  44.419190     NaN
  263  79.417850  79.417850  79.417850  79.417850  79.417850  79.417850     NaN
  264  32.063923  32.063923  32.063923  32.063923  32.063923  32.063923     NaN
  265  41.876696  41.876696  41.876696  41.876696  41.876696  41.876696     NaN

  [266 rows x 63 columns]],
 ['AG.LND.ARBL.HA',
  {'id': 'AG.LND.ARBL.HA', 'value': 'Arable land (hectares)'},
  0.8717948717948718,
  0.8559322033898306,
      economy  YR1960      YR1961      YR1962      YR1963      YR1964  \
  0       ABW     NaN      2000.0      2000.0      2000.0      2000.0
  1       AFE     NaN         NaN         NaN         NaN         NaN
  2       AFG     NaN   7650000.0   7700000.0   7750000.0   7800000.0
  3       AFW     NaN         NaN         NaN         NaN         NaN
  4       AGO     NaN   2670000.0   2700000.0   2720000.0   2750000.0
  ..      ...     ...         ...         ...         ...         ...
  261     XKX     NaN         NaN         NaN         NaN         NaN
  262     YEM     NaN   1262000.0   1273000.0   1285000.0   1295000.0
  263     ZAF     NaN  12000000.0  12050000.0  12100000.0  12150000.0
  264     ZMB     NaN   2549000.0   2552000.0   2576000.0   2601000.0
  265     ZWE     NaN   1885000.0   1935000.0   1985000.0   2035000.0

           YR1965      YR1966      YR1967      YR1968  ...      YR2012  \
  0        2000.0      2000.0      2000.0      2000.0  ...      2000.0
  1           NaN         NaN         NaN         NaN  ...         NaN
  2     7800000.0   7835000.0   7844000.0   7844000.0  ...   7790000.0
  3           NaN         NaN         NaN         NaN  ...         NaN
  4     2770000.0   2800000.0   2830000.0   2860000.0  ...   4700000.0
  ..          ...         ...         ...         ...  ...         ...
  261         NaN         NaN         NaN         NaN  ...         NaN
  262   1305000.0   1310000.0   1317000.0   1322000.0  ...   1204000.0
  263  12200000.0  12209000.0  12218000.0  12227000.0  ...  12000000.0
  264   2604000.0   2658000.0   2672000.0   2705000.0  ...   3800000.0
  265   2065000.0   2135000.0   2185000.0   2235000.0  ...   4000000.0

           YR2013      YR2014      YR2015      YR2016      YR2017      YR2018  \
  0        2000.0      2000.0      2000.0      2000.0      2000.0      2000.0
  1           NaN         NaN         NaN         NaN         NaN         NaN
  2     7785000.0   7771000.0   7765000.0   7729000.0   7699000.0   7794000.0
  3           NaN         NaN         NaN         NaN         NaN         NaN
  4     4900000.0   4900000.0   4900000.0   4900000.0   4900000.0   4900000.0
  ..          ...         ...         ...         ...         ...         ...
  261         NaN         NaN         NaN         NaN         NaN         NaN
  262   1201000.0   1153600.0   1137600.0   1095800.0   1163000.0   1167000.0
  263  12000000.0  12000000.0  12000000.0  12000000.0  12000000.0  12000000.0
  264   3700000.0   3800000.0   3800000.0   3800000.0   3800000.0   3800000.0
  265   4000000.0   4000000.0   4000000.0   4000000.0   4000000.0   4000000.0

           YR2019      YR2020  YR2021
  0        2000.0      2000.0     NaN
  1           NaN         NaN     NaN
  2     7788000.0   7829000.0     NaN
  3           NaN         NaN     NaN
  4     4900000.0   4900000.0     NaN
  ..          ...         ...     ...
  261         NaN         NaN     NaN
  262   1158000.0   1158000.0     NaN
  263  12000000.0  12000000.0     NaN
  264   3800000.0   3800000.0     NaN
  265   4000000.0   4000000.0     NaN

  [266 rows x 63 columns]],
 ['AG.LND.ARBL.HA.PC',
  {'id': 'AG.LND.ARBL.HA.PC', 'value': 'Arable land (hectares per person)'},
  0.8717948717948718,
  0.8559322033898306,
      economy  YR1960    YR1961    YR1962    YR1963    YR1964    YR1965  \
  0       ABW     NaN  0.035835  0.035285  0.034798  0.034377  0.034024
  1       AFE     NaN  0.470616  0.459786  0.460258  0.453666  0.443934
  2       AFG     NaN  0.870293  0.858508  0.846304  0.833733  0.815461
  3       AFW     NaN  0.636179  0.631061  0.639804  0.635694  0.642833
  4       AGO     NaN  0.490689  0.489006  0.485729  0.484735  0.482866
  ..      ...     ...       ...       ...       ...       ...       ...
  261     XKX     NaN       NaN       NaN       NaN       NaN       NaN
  262     YEM     NaN  0.223495  0.221261  0.219276  0.216780  0.214029
  263     ZAF     NaN  0.706320  0.688448  0.670649  0.653117  0.635841
  264     ZMB     NaN  0.791750  0.767882  0.750718  0.734173  0.711860
  265     ZWE     NaN  0.480138  0.477804  0.475116  0.472121  0.464342

         YR1966    YR1967    YR1968  ...    YR2012    YR2013    YR2014  \
  0    0.033732  0.033601  0.033630  ...  0.019586  0.019440  0.019306
  1    0.433791  0.422904  0.414237  ...  0.210967  0.206580  0.202699
  2    0.800867  0.783614  0.765434  ...  0.255691  0.246820  0.237528
  3    0.627829  0.614401  0.608332  ...  0.260101  0.257463  0.250441
  4    0.483839  0.485628  0.487372  ...  0.186595  0.187402  0.180623
  ..        ...       ...       ...  ...       ...       ...       ...
  261       NaN       NaN       NaN  ...       NaN       NaN       NaN
  262  0.210326  0.206815  0.202888  ...  0.045913  0.044508  0.041566
  263  0.616935  0.598608  0.580840  ...  0.225797  0.222744  0.219260

In [5]:
coverage_dict = {}

for item in coverage:
    coverage_dict[item[0]] = item[4]

In [7]:
with open('all_wb_indicators_dict.pickle', 'wb') as handle:
    pkl.dump(coverage_dict, handle)